# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coordinator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\x0b\x63oordinator\"0\n\x0c\x63ont_request\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x12\n\nworld_rank\x18\x02 \x01(\x05\"4\n\rcont_response\x12\x13\n\x0b\x61\x63tive_list\x18\x01 \x03(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x05\"0\n\x0chook_request\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x12\n\nworld_rank\x18\x02 \x01(\x05\"$\n\rhook_response\x12\x13\n\x0b\x61\x63tive_list\x18\x01 \x03(\x05\x32\xa1\x01\n\x0b\x43oordinator\x12K\n\x10\x63ontroller_fetch\x12\x19.coordinator.cont_request\x1a\x1a.coordinator.cont_response\"\x00\x12\x45\n\nhook_fetch\x12\x19.coordinator.hook_request\x1a\x1a.coordinator.hook_response\"\x00\x42\x37\n\x15io.grpc.examples.testB\x10\x43oordinatorProtoP\x01\xa2\x02\tCoorditorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025io.grpc.examples.testB\020CoordinatorProtoP\001\242\002\tCoorditor'
  _globals['_CONT_REQUEST']._serialized_start=34
  _globals['_CONT_REQUEST']._serialized_end=82
  _globals['_CONT_RESPONSE']._serialized_start=84
  _globals['_CONT_RESPONSE']._serialized_end=136
  _globals['_HOOK_REQUEST']._serialized_start=138
  _globals['_HOOK_REQUEST']._serialized_end=186
  _globals['_HOOK_RESPONSE']._serialized_start=188
  _globals['_HOOK_RESPONSE']._serialized_end=224
  _globals['_COORDINATOR']._serialized_start=227
  _globals['_COORDINATOR']._serialized_end=388
# @@protoc_insertion_point(module_scope)
